Don't create dummy index.html for webapp #25
owncloud/ocis-konnectd pull request #28
Opened 2020-02-19 14:22 UTC by IljaN

Downstream does not require webapp anymore

Depends on https://github.com/Kopano-dev/konnect/pull/27 to be merged first

2020-02-19 14:51 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/service.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5033240&bid=16581615)

2020-02-28 17:14 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/service.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5033240&bid=16581615)

2020-02-28 17:57 UTC, micbar requested changes

2020-02-28 17:57 UTC, micbar commented on pkg/flagset/flagset.go
> +			Name:        "disable-identifier-webapp",
This Flag and ENV variable needs to be documented it `getting-started.md`

2020-03-02 07:59 UTC, refs requested changes
documentation and changelog 💃

2020-03-03 18:16 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/service.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5033240&bid=16581615)

2020-03-03 18:29 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/service.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5033240&bid=16581615)

2020-03-03 18:38 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/service.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5033240&bid=16581615)

2020-03-03 18:40 UTC, IljaN commented
This PR is based against https://github.com/owncloud/ocis-konnectd/pull/46 which contains intial docs. Please merge it first.

2020-03-03 18:47 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/service.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5033240&bid=16581615)

2020-03-03 18:48 UTC, refs approved these changes

2020-03-09 18:44 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/service.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5033240&bid=16581615)

2020-03-09 18:49 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ pkg/service/v0/service.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-konnectd/pullRequest?prid=5033240&bid=16581615)

2020-03-09 18:52 UTC, micbar approved these changes

2020-03-09 18:54 UTC, merged